export type OpenCodeRolePermission = Record<string, unknown>

// Politicas funcionales por rol. Las denegaciones de secretos se aplican aparte.
const ROLE_PERMISSIONS: Record<string, OpenCodeRolePermission> = {
  "ms-architect": {
    "edit": "deny",
    "bash": {
      "*": "deny",
      "pwd": "allow",
      "ls": "allow",
      "ls *": "allow",
      "wc *": "allow",
      "file *": "allow",
      "stat *": "allow",
      "jq *": "allow",
      "rg *": "allow",
      "grep *": "allow",
      "git status": "allow",
      "git status *": "allow",
      "git diff*": "allow",
      "git show*": "allow",
      "git log*": "allow",
      "git branch*": "allow",
      "git rev-parse*": "allow",
      "opencode debug config": "allow",
      "opencode debug agent *": "allow",
      "opencode debug skill": "allow"
    },
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "allow",
    "question": "allow",
    "task": {
      "*": "deny",
      "ms-spec": "allow",
      "ms-designer": "allow",
      "ms-codex": "allow",
      "ms-fastlane": "allow",
      "ms-tester": "allow",
      "ms-scout": "allow",
      "ms-debugger": "allow",
      "ms-progress": "allow",
      "ms-writer": "allow",
      "ms-security-auditor": "allow"
    }
  },
  "ms-codex": {
    "edit": "allow",
    "bash": {
      "*": "ask",
      "ls": "allow",
      "ls *": "allow",
      "pwd": "allow",
      "cat *": "allow",
      "head *": "allow",
      "tail *": "allow",
      "wc *": "allow",
      "file *": "allow",
      "stat *": "allow",
      "find *": "allow",
      "tree *": "allow",
      "mkdir -p .atl": "allow",
      "mkdir -p .atl/": "allow",
      "rg *": "allow",
      "grep *": "allow",
      "git status": "allow",
      "git status *": "allow",
      "git diff*": "allow",
      "git log*": "allow",
      "git show*": "allow",
      "git blame*": "allow",
      "git branch*": "allow",
      "git rev-parse*": "allow",
      "node --version": "allow",
      "npm --version": "allow",
      "npm test*": "allow",
      "npm run test*": "allow",
      "npm run lint*": "allow",
      "npm run type*": "allow",
      "npm run typecheck*": "allow",
      "npm run check*": "allow",
      "npm run format*": "allow",
      "pnpm --version": "allow",
      "pnpm test*": "allow",
      "pnpm lint*": "allow",
      "pnpm type*": "allow",
      "pnpm typecheck*": "allow",
      "pnpm check*": "allow",
      "pnpm format:check*": "allow",
      "pnpm run test*": "allow",
      "pnpm run lint*": "allow",
      "pnpm run type*": "allow",
      "pnpm run typecheck*": "allow",
      "pnpm run check*": "allow",
      "pnpm run format*": "allow",
      "pnpm exec eslint*": "allow",
      "pnpm exec tsc *--noEmit*": "allow",
      "pnpm exec vue-tsc*": "allow",
      "pnpm exec prettier --check*": "allow",
      "pnpm exec prettier -c*": "allow",
      "pnpm exec vitest run*": "allow",
      "pnpm exec jest*": "allow",
      "pnpm exec stylelint*": "allow",
      "pnpm exec biome check*": "allow",
      "pnpm exec oxlint*": "allow",
      "pnpm exec svelte-check*": "allow",
      "pnpm exec astro check*": "allow",
      "npx --no-install eslint*": "allow",
      "npx --no-install tsc *--noEmit*": "allow",
      "npx --no-install prettier --check*": "allow",
      "npx --no-install prettier -c*": "allow",
      "npx --no-install vitest run*": "allow",
      "npx --no-install jest*": "allow",
      "yarn --version": "allow",
      "yarn test*": "allow",
      "yarn run test*": "allow",
      "yarn run lint*": "allow",
      "yarn run type*": "allow",
      "yarn run typecheck*": "allow",
      "yarn run check*": "allow",
      "yarn run format*": "allow",
      "bun --version": "allow",
      "bun test*": "allow",
      "bun run test*": "allow",
      "bun run lint*": "allow",
      "bun run type*": "allow",
      "bun run typecheck*": "allow",
      "bun run check*": "allow",
      "bun run format*": "allow",
      "python --version": "allow",
      "python3 --version": "allow",
      "pytest*": "allow",
      "python -m pytest*": "allow",
      "python3 -m pytest*": "allow",
      "uv run pytest*": "allow",
      "uv run --frozen pytest*": "allow",
      "uv run --locked pytest*": "allow",
      "uv run ruff check*": "allow",
      "uv run --frozen ruff check*": "allow",
      "uv run --locked ruff check*": "allow",
      "uv run ruff format --check*": "allow",
      "uv run --frozen ruff format --check*": "allow",
      "uv run --locked ruff format --check*": "allow",
      "uv run mypy*": "allow",
      "uv run --frozen mypy*": "allow",
      "uv run --locked mypy*": "allow",
      "uv run pyright*": "allow",
      "uv run --frozen pyright*": "allow",
      "uv run --locked pyright*": "allow",
      "ruff check*": "allow",
      "ruff format*": "allow",
      "black *": "allow",
      "mypy*": "allow",
      "pyright*": "allow",
      "go version": "allow",
      "go test*": "allow",
      "go vet*": "allow",
      "gofmt*": "allow",
      "cargo --version": "allow",
      "cargo test*": "allow",
      "cargo check*": "allow",
      "cargo clippy*": "allow",
      "cargo fmt*": "allow",
      "make test*": "allow",
      "PYTEST_ADDOPTS=* make test*": "allow",
      "PYTEST_ADDOPTS=* pytest*": "allow",
      "PYTEST_ADDOPTS=* python -m pytest*": "allow",
      "PYTEST_ADDOPTS=* python3 -m pytest*": "allow",
      "PYTEST_ADDOPTS=* uv run pytest*": "allow",
      "make lint*": "allow",
      "make type*": "allow",
      "make check*": "allow",
      "make format*": "allow",
      "rm -rf*": "deny",
      "rm -fr*": "deny",
      "rm -r *": "deny",
      "rm -f *": "deny",
      "dd *": "deny",
      "mkfs*": "deny",
      "fdisk*": "deny",
      "shred*": "deny",
      "wipe*": "deny",
      "chmod -R *": "deny",
      "chown -R *": "deny",
      "eval *": "deny",
      "curl *| sh*": "deny",
      "curl *| bash*": "deny",
      "wget *| sh*": "deny",
      "wget *| bash*": "deny",
      "bash -c *curl*": "ask",
      "sh -c *curl*": "ask",
      "base64 -d *": "ask",
      "base64 --decode *": "ask",
      "nc *": "ask",
      "netcat *": "ask",
      "ssh *": "ask",
      "scp *": "ask",
      "git push*": "ask",
      "git push --force*": "deny",
      "git push -f*": "deny",
      "git reset --hard*": "deny",
      "git checkout -- *": "deny",
      "git checkout .": "deny",
      "git restore *": "deny",
      "git restore .": "deny",
      "git clean -f*": "deny",
      "git branch -D*": "deny",
      "git commit*--no-verify*": "deny",
      "git commit* -n*": "deny",
      "git commit*--no-gpg-sign*": "deny",
      "sudo *": "deny",
      "npm install*": "ask",
      "npm i *": "ask",
      "npm uninstall*": "ask",
      "pnpm install*": "ask",
      "pnpm add*": "ask",
      "pnpm remove*": "ask",
      "yarn add*": "ask",
      "yarn remove*": "ask",
      "bun add*": "ask",
      "bun remove*": "ask",
      "pip install*": "ask",
      "pip uninstall*": "ask",
      "uv pip install*": "ask",
      "uv add*": "ask",
      "uv remove*": "ask",
      "poetry add*": "ask",
      "poetry remove*": "ask",
      "cargo add*": "ask",
      "cargo remove*": "ask",
      "go get*": "ask",
      "go install*": "ask",
      "brew install*": "ask",
      "apt install*": "ask",
      "apt-get install*": "ask"
    },
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "deny",
    "task": {
      "*": "deny"
    }
  },
  "ms-debugger": {
    "edit": "deny",
    "bash": {
      "*": "ask",
      "ls *": "allow",
      "ls": "allow",
      "pwd": "allow",
      "cat *": "allow",
      "head *": "allow",
      "tail *": "allow",
      "wc *": "allow",
      "file *": "allow",
      "stat *": "allow",
      "find *": "allow",
      "tree *": "allow",
      "rg *": "allow",
      "grep *": "allow",
      "ps *": "allow",
      "ps": "allow",
      "which *": "allow",
      "type *": "allow",
      "git status": "allow",
      "git status *": "allow",
      "git log*": "allow",
      "git diff*": "allow",
      "git show*": "allow",
      "git blame*": "allow",
      "git branch*": "allow",
      "git rev-parse*": "allow",
      "git config --get *": "allow",
      "node --version": "allow",
      "npm --version": "allow",
      "npm ls*": "allow",
      "npm run *": "ask",
      "pnpm run *": "ask",
      "pnpm exec *": "ask",
      "yarn run *": "ask",
      "yarn *": "ask",
      "bun run *": "ask",
      "make *": "ask",
      "npm test*": "allow",
      "npm run test*": "allow",
      "npm run lint*": "allow",
      "npm run type*": "allow",
      "npm run typecheck*": "allow",
      "npm run check*": "allow",
      "npm run format:check*": "allow",
      "yarn --version": "allow",
      "yarn test*": "allow",
      "yarn run test*": "allow",
      "yarn run lint*": "allow",
      "yarn run type*": "allow",
      "yarn run typecheck*": "allow",
      "yarn run check*": "allow",
      "yarn run format:check*": "allow",
      "pnpm --version": "allow",
      "pnpm test*": "allow",
      "pnpm lint*": "allow",
      "pnpm type*": "allow",
      "pnpm typecheck*": "allow",
      "pnpm check*": "allow",
      "pnpm format:check*": "allow",
      "pnpm run test*": "allow",
      "pnpm run lint*": "allow",
      "pnpm run type*": "allow",
      "pnpm run typecheck*": "allow",
      "pnpm run check*": "allow",
      "pnpm run format:check*": "allow",
      "pnpm ls*": "allow",
      "bun --version": "allow",
      "bun test*": "allow",
      "bun run test*": "allow",
      "bun run lint*": "allow",
      "bun run type*": "allow",
      "bun run typecheck*": "allow",
      "bun run check*": "allow",
      "bun run format:check*": "allow",
      "make test*": "allow",
      "make lint*": "allow",
      "make type*": "allow",
      "make check*": "allow",
      "python --version": "allow",
      "python3 --version": "allow",
      "pytest*": "allow",
      "python -m pytest*": "allow",
      "python3 -m pytest*": "allow",
      "pip list*": "allow",
      "uv pip list*": "allow",
      "poetry --version": "allow",
      "go version": "allow",
      "go env*": "allow",
      "rustc --version": "allow",
      "cargo --version": "allow",
      "docker ps*": "allow",
      "docker logs*": "ask",
      "docker inspect*": "ask",
      "kubectl get*": "allow",
      "kubectl describe*": "ask",
      "kubectl logs*": "ask",
      "curl -*I*": "allow",
      "*--fix*": "deny",
      "*--autofix*": "deny",
      "*--write*": "deny",
      "*--update-snapshot*": "deny",
      "*--updateSnapshot*": "deny",
      "npm run *:fix*": "deny",
      "pnpm run *:fix*": "deny",
      "yarn run *:fix*": "deny",
      "bun run *:fix*": "deny",
      "npm test* -u*": "deny",
      "npm run test* -u*": "deny",
      "pnpm test* -u*": "deny",
      "pnpm run test* -u*": "deny",
      "yarn test* -u*": "deny",
      "yarn run test* -u*": "deny",
      "bun test* -u*": "deny",
      "bun run test* -u*": "deny",
      "make *fix*": "deny",
      "rm -rf*": "deny",
      "rm -fr*": "deny",
      "git push*": "deny",
      "git reset --hard*": "deny",
      "git checkout -- *": "deny",
      "git checkout .": "deny",
      "git clean -f*": "deny",
      "git commit*": "deny",
      "sudo *": "deny",
      "npm install*": "deny",
      "pnpm install*": "deny",
      "pip install*": "deny",
      "uv pip install*": "deny"
    },
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "deny",
    "task": {
      "*": "deny"
    }
  },
  "ms-designer": {
    "edit": {
      "*": "deny",
      "docs/design/*.md": "allow",
      "docs/design/**/*.md": "allow"
    },
    "bash": "deny",
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "allow",
    "task": {
      "*": "deny"
    }
  },
  "ms-discovery": {
    "edit": {
      "*": "deny",
      "docs/discovery/*.md": "allow",
      "docs/discovery/**/*.md": "allow"
    },
    "bash": "deny",
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "deny",
    "question": "allow",
    "task": {
      "*": "deny"
    }
  },
  "ms-fastlane": {
    "edit": "allow",
    "bash": {
      "*": "ask",
      "ls": "allow",
      "ls *": "allow",
      "pwd": "allow",
      "git status": "allow",
      "git status *": "allow",
      "git diff*": "allow",
      "git log*": "allow",
      "git show*": "allow",
      "npm test*": "allow",
      "npm run test*": "allow",
      "npm run lint*": "allow",
      "npm run type*": "allow",
      "npm run typecheck*": "allow",
      "npm run check*": "allow",
      "npm run format*": "allow",
      "pnpm test*": "allow",
      "pnpm lint*": "allow",
      "pnpm type*": "allow",
      "pnpm typecheck*": "allow",
      "pnpm check*": "allow",
      "pnpm format:check*": "allow",
      "pnpm run test*": "allow",
      "pnpm run lint*": "allow",
      "pnpm run type*": "allow",
      "pnpm run typecheck*": "allow",
      "pnpm run check*": "allow",
      "pnpm run format*": "allow",
      "pnpm exec eslint*": "allow",
      "pnpm exec tsc *--noEmit*": "allow",
      "pnpm exec vue-tsc*": "allow",
      "pnpm exec prettier --check*": "allow",
      "pnpm exec prettier -c*": "allow",
      "pnpm exec vitest run*": "allow",
      "pnpm exec jest*": "allow",
      "pnpm exec stylelint*": "allow",
      "pnpm exec biome check*": "allow",
      "pnpm exec oxlint*": "allow",
      "pnpm exec svelte-check*": "allow",
      "pnpm exec astro check*": "allow",
      "npx --no-install eslint*": "allow",
      "npx --no-install tsc *--noEmit*": "allow",
      "npx --no-install prettier --check*": "allow",
      "npx --no-install prettier -c*": "allow",
      "npx --no-install vitest run*": "allow",
      "npx --no-install jest*": "allow",
      "yarn test*": "allow",
      "yarn run test*": "allow",
      "yarn run lint*": "allow",
      "yarn run type*": "allow",
      "yarn run typecheck*": "allow",
      "yarn run check*": "allow",
      "yarn run format*": "allow",
      "bun test*": "allow",
      "bun run test*": "allow",
      "bun run lint*": "allow",
      "bun run type*": "allow",
      "bun run typecheck*": "allow",
      "bun run check*": "allow",
      "bun run format*": "allow",
      "pytest*": "allow",
      "python -m pytest*": "allow",
      "python3 -m pytest*": "allow",
      "uv run pytest*": "allow",
      "uv run --frozen pytest*": "allow",
      "uv run --locked pytest*": "allow",
      "uv run ruff check*": "allow",
      "uv run --frozen ruff check*": "allow",
      "uv run --locked ruff check*": "allow",
      "uv run ruff format --check*": "allow",
      "uv run --frozen ruff format --check*": "allow",
      "uv run --locked ruff format --check*": "allow",
      "uv run mypy*": "allow",
      "uv run --frozen mypy*": "allow",
      "uv run --locked mypy*": "allow",
      "uv run pyright*": "allow",
      "uv run --frozen pyright*": "allow",
      "uv run --locked pyright*": "allow",
      "ruff check*": "allow",
      "ruff format*": "allow",
      "black *": "allow",
      "mypy*": "allow",
      "pyright*": "allow",
      "go test*": "allow",
      "go vet*": "allow",
      "gofmt*": "allow",
      "cargo test*": "allow",
      "cargo check*": "allow",
      "cargo clippy*": "allow",
      "cargo fmt*": "allow",
      "make test*": "allow",
      "PYTEST_ADDOPTS=* make test*": "allow",
      "PYTEST_ADDOPTS=* pytest*": "allow",
      "PYTEST_ADDOPTS=* python -m pytest*": "allow",
      "PYTEST_ADDOPTS=* python3 -m pytest*": "allow",
      "PYTEST_ADDOPTS=* uv run pytest*": "allow",
      "make lint*": "allow",
      "make type*": "allow",
      "make check*": "allow",
      "make format*": "allow",
      "rm -rf*": "deny",
      "rm -fr*": "deny",
      "git push*": "deny",
      "git reset --hard*": "deny",
      "git checkout -- *": "deny",
      "git checkout .": "deny",
      "git restore *": "deny",
      "git restore .": "deny",
      "git clean -f*": "deny",
      "git commit*": "deny",
      "sudo *": "deny",
      "npm install*": "deny",
      "npm i *": "deny",
      "pnpm install*": "deny",
      "pnpm add*": "deny",
      "yarn add*": "deny",
      "bun add*": "deny",
      "pip install*": "deny",
      "uv add*": "deny",
      "poetry add*": "deny",
      "cargo add*": "deny",
      "go get*": "deny"
    },
    "webfetch": "deny",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "deny",
    "task": {
      "*": "deny"
    }
  },
  "ms-plan": {
    "edit": {
      "*": "deny",
      "docs/prd/*.md": "allow",
      "docs/prd/**/*.md": "allow"
    },
    "bash": "deny",
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "deny",
    "question": "allow",
    "task": {
      "*": "deny"
    }
  },
  "ms-progress": {
    "edit": {
      "*": "deny",
      "docs/status/*.md": "allow",
      "docs/status/**/*.md": "allow"
    },
    "bash": "deny",
    "webfetch": "deny",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "deny",
    "task": {
      "*": "deny"
    }
  },
  "ms-scout": {
    "edit": "deny",
    "bash": {
      "*": "deny",
      "pwd": "allow",
      "ls": "allow",
      "ls *": "allow",
      "cat *": "allow",
      "head *": "allow",
      "tail *": "allow",
      "wc *": "allow",
      "file *": "allow",
      "stat *": "allow",
      "find *": "allow",
      "tree *": "allow",
      "rg *": "allow",
      "grep *": "allow",
      "git status": "allow",
      "git status *": "allow",
      "git diff*": "allow",
      "git show*": "allow",
      "git log*": "allow",
      "git branch*": "allow",
      "git rev-parse*": "allow"
    },
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "deny",
    "task": {
      "*": "deny"
    }
  },
  "ms-security-auditor": {
    "edit": "deny",
    "bash": {
      "*": "deny",
      "ls": "allow",
      "ls *": "allow",
      "pwd": "allow",
      "cat *": "allow",
      "head *": "allow",
      "tail *": "allow",
      "wc *": "allow",
      "file *": "allow",
      "stat *": "allow",
      "find *": "allow",
      "tree *": "allow",
      "grep *": "allow",
      "rg *": "allow",
      "git status": "allow",
      "git status *": "allow",
      "git log*": "allow",
      "git diff*": "allow",
      "git show*": "allow",
      "git blame*": "allow",
      "git branch*": "allow",
      "git rev-parse*": "allow",
      "node --version": "allow",
      "npm --version": "allow",
      "npm ls*": "allow",
      "npm audit*": "allow",
      "pnpm --version": "allow",
      "pnpm ls*": "allow",
      "pnpm audit*": "allow",
      "yarn audit*": "allow",
      "bun pm ls*": "allow",
      "python --version": "allow",
      "python3 --version": "allow",
      "pip list*": "allow",
      "pip-audit*": "allow",
      "safety check*": "allow",
      "uv pip list*": "allow",
      "poetry show*": "allow",
      "cargo audit*": "allow",
      "cargo tree*": "allow",
      "cargo --version": "allow",
      "go version": "allow",
      "go list*": "allow",
      "govulncheck*": "allow",
      "osv-scanner*": "allow",
      "trivy*": "allow",
      "semgrep*": "allow",
      "bandit*": "allow",
      "gitleaks detect*": "allow",
      "trufflehog*": "allow",
      "*--fix*": "deny",
      "*--autofix*": "deny",
      "*--write*": "deny",
      "npm audit fix*": "deny",
      "npm audit*--fix*": "deny",
      "pnpm audit*--fix*": "deny",
      "yarn audit*--fix*": "deny",
      "semgrep*--autofix*": "deny",
      "semgrep*--fix*": "deny"
    },
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "deny",
    "task": {
      "*": "deny"
    }
  },
  "ms-spec": {
    "edit": {
      "*": "deny",
      "docs/spec/*.md": "allow",
      "docs/spec/**/*.md": "allow"
    },
    "bash": "deny",
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "allow",
    "task": {
      "*": "deny"
    }
  },
  "ms-tester": {
    "edit": "deny",
    "bash": {
      "*": "ask",
      "ls": "allow",
      "ls *": "allow",
      "pwd": "allow",
      "cat *": "allow",
      "head *": "allow",
      "tail *": "allow",
      "wc *": "allow",
      "file *": "allow",
      "stat *": "allow",
      "find *": "allow",
      "tree *": "allow",
      "rg *": "allow",
      "grep *": "allow",
      "git status": "allow",
      "git status *": "allow",
      "git diff*": "allow",
      "git log*": "allow",
      "git show*": "allow",
      "node --version": "allow",
      "npm --version": "allow",
      "npm test*": "allow",
      "npm run test*": "allow",
      "npm run lint*": "allow",
      "npm run type*": "allow",
      "npm run typecheck*": "allow",
      "npm run check*": "allow",
      "npm run eslint*": "allow",
      "npm run format:check*": "allow",
      "pnpm --version": "allow",
      "pnpm test*": "allow",
      "pnpm lint*": "allow",
      "pnpm type*": "allow",
      "pnpm typecheck*": "allow",
      "pnpm check*": "allow",
      "pnpm format:check*": "allow",
      "pnpm run test*": "allow",
      "pnpm run lint*": "allow",
      "pnpm run type*": "allow",
      "pnpm run typecheck*": "allow",
      "pnpm run check*": "allow",
      "pnpm run eslint*": "allow",
      "pnpm run format:check*": "allow",
      "pnpm exec eslint*": "allow",
      "pnpm exec tsc *--noEmit*": "allow",
      "pnpm exec vue-tsc*": "allow",
      "pnpm exec prettier --check*": "allow",
      "pnpm exec prettier -c*": "allow",
      "pnpm exec vitest run*": "allow",
      "pnpm exec jest*": "allow",
      "pnpm exec stylelint*": "allow",
      "pnpm exec biome check*": "allow",
      "pnpm exec oxlint*": "allow",
      "pnpm exec svelte-check*": "allow",
      "pnpm exec astro check*": "allow",
      "yarn --version": "allow",
      "yarn test*": "allow",
      "yarn run test*": "allow",
      "yarn run lint*": "allow",
      "yarn run type*": "allow",
      "yarn run typecheck*": "allow",
      "yarn run check*": "allow",
      "yarn run eslint*": "allow",
      "yarn run format:check*": "allow",
      "yarn eslint*": "allow",
      "yarn tsc *--noEmit*": "allow",
      "yarn prettier --check*": "allow",
      "yarn prettier -c*": "allow",
      "yarn vitest run*": "allow",
      "yarn jest*": "allow",
      "yarn stylelint*": "allow",
      "bun --version": "allow",
      "bun test*": "allow",
      "bun run test*": "allow",
      "bun run lint*": "allow",
      "bun run type*": "allow",
      "bun run typecheck*": "allow",
      "bun run check*": "allow",
      "bun run eslint*": "allow",
      "bun run format:check*": "allow",
      "eslint*": "allow",
      "./node_modules/.bin/eslint*": "allow",
      "node_modules/.bin/eslint*": "allow",
      "tsc *--noEmit*": "allow",
      "./node_modules/.bin/tsc *--noEmit*": "allow",
      "node_modules/.bin/tsc *--noEmit*": "allow",
      "vue-tsc*": "allow",
      "./node_modules/.bin/vue-tsc*": "allow",
      "node_modules/.bin/vue-tsc*": "allow",
      "prettier --check*": "allow",
      "prettier -c*": "allow",
      "./node_modules/.bin/prettier --check*": "allow",
      "./node_modules/.bin/prettier -c*": "allow",
      "node_modules/.bin/prettier --check*": "allow",
      "node_modules/.bin/prettier -c*": "allow",
      "vitest run*": "allow",
      "vitest --run*": "allow",
      "./node_modules/.bin/vitest run*": "allow",
      "./node_modules/.bin/vitest --run*": "allow",
      "node_modules/.bin/vitest run*": "allow",
      "node_modules/.bin/vitest --run*": "allow",
      "jest*": "allow",
      "./node_modules/.bin/jest*": "allow",
      "node_modules/.bin/jest*": "allow",
      "stylelint*": "allow",
      "./node_modules/.bin/stylelint*": "allow",
      "node_modules/.bin/stylelint*": "allow",
      "biome check*": "allow",
      "./node_modules/.bin/biome check*": "allow",
      "node_modules/.bin/biome check*": "allow",
      "oxlint*": "allow",
      "./node_modules/.bin/oxlint*": "allow",
      "node_modules/.bin/oxlint*": "allow",
      "svelte-check*": "allow",
      "./node_modules/.bin/svelte-check*": "allow",
      "node_modules/.bin/svelte-check*": "allow",
      "astro check*": "allow",
      "./node_modules/.bin/astro check*": "allow",
      "node_modules/.bin/astro check*": "allow",
      "next lint*": "allow",
      "./node_modules/.bin/next lint*": "allow",
      "node_modules/.bin/next lint*": "allow",
      "npx --no-install eslint*": "allow",
      "npx --no-install tsc *--noEmit*": "allow",
      "npx --no-install prettier --check*": "allow",
      "npx --no-install prettier -c*": "allow",
      "npx --no-install vitest run*": "allow",
      "npx --no-install jest*": "allow",
      "python --version": "allow",
      "python3 --version": "allow",
      "pytest*": "allow",
      "python -m pytest*": "allow",
      "python3 -m pytest*": "allow",
      "uv run pytest*": "allow",
      "uv run --frozen pytest*": "allow",
      "uv run --locked pytest*": "allow",
      "uv run ruff check*": "allow",
      "uv run --frozen ruff check*": "allow",
      "uv run --locked ruff check*": "allow",
      "uv run ruff format --check*": "allow",
      "uv run --frozen ruff format --check*": "allow",
      "uv run --locked ruff format --check*": "allow",
      "uv run black --check*": "allow",
      "uv run --frozen black --check*": "allow",
      "uv run --locked black --check*": "allow",
      "uv run mypy*": "allow",
      "uv run --frozen mypy*": "allow",
      "uv run --locked mypy*": "allow",
      "uv run pyright*": "allow",
      "uv run --frozen pyright*": "allow",
      "uv run --locked pyright*": "allow",
      "ruff check*": "allow",
      "black --check*": "allow",
      "mypy*": "allow",
      "pyright*": "allow",
      "go version": "allow",
      "go test*": "allow",
      "go vet*": "allow",
      "mvn test*": "allow",
      "mvn -q test*": "allow",
      "mvn verify*": "allow",
      "mvn -q verify*": "allow",
      "./mvnw test*": "allow",
      "./mvnw -q test*": "allow",
      "./mvnw verify*": "allow",
      "./mvnw -q verify*": "allow",
      "gradle test*": "allow",
      "gradle check*": "allow",
      "./gradlew test*": "allow",
      "./gradlew check*": "allow",
      "cargo --version": "allow",
      "cargo test*": "allow",
      "cargo check*": "allow",
      "cargo clippy*": "allow",
      "cargo fmt --check*": "allow",
      "make test*": "allow",
      "PYTEST_ADDOPTS=* make test*": "allow",
      "PYTEST_ADDOPTS=* pytest*": "allow",
      "PYTEST_ADDOPTS=* python -m pytest*": "allow",
      "PYTEST_ADDOPTS=* python3 -m pytest*": "allow",
      "PYTEST_ADDOPTS=* uv run pytest*": "allow",
      "make lint*": "allow",
      "make type*": "allow",
      "make check*": "allow",
      "make format-check*": "allow",
      "rm -rf*": "deny",
      "rm -fr*": "deny",
      "git push*": "deny",
      "git reset --hard*": "deny",
      "git checkout -- *": "deny",
      "git checkout .": "deny",
      "git restore *": "deny",
      "git restore .": "deny",
      "git clean -f*": "deny",
      "git commit*": "deny",
      "git branch -D*": "deny",
      "sudo *": "deny",
      "npm install*": "deny",
      "npm i *": "deny",
      "npm uninstall*": "deny",
      "pnpm install*": "deny",
      "pnpm add*": "deny",
      "pnpm remove*": "deny",
      "yarn add*": "deny",
      "yarn remove*": "deny",
      "bun add*": "deny",
      "bun remove*": "deny",
      "pip install*": "deny",
      "pip uninstall*": "deny",
      "uv pip install*": "deny",
      "uv add*": "deny",
      "uv remove*": "deny",
      "poetry add*": "deny",
      "poetry remove*": "deny",
      "cargo add*": "deny",
      "cargo remove*": "deny",
      "go get*": "deny",
      "go install*": "deny",
      "brew install*": "deny",
      "apt install*": "deny",
      "apt-get install*": "deny",
      "*--fix*": "deny",
      "*--autofix*": "deny",
      "*--write*": "deny",
      "*--update-snapshot*": "deny",
      "*--updateSnapshot*": "deny",
      "npm run *:fix*": "deny",
      "pnpm run *:fix*": "deny",
      "yarn run *:fix*": "deny",
      "bun run *:fix*": "deny",
      "npm test* -u*": "deny",
      "npm run test* -u*": "deny",
      "pnpm test* -u*": "deny",
      "pnpm run test* -u*": "deny",
      "yarn test* -u*": "deny",
      "yarn run test* -u*": "deny",
      "bun test* -u*": "deny",
      "bun run test* -u*": "deny",
      "make *fix*": "deny"
    },
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "deny",
    "task": {
      "*": "deny"
    }
  },
  "ms-writer": {
    "edit": {
      "*": "deny",
      "README.md": "allow",
      "CHANGELOG.md": "allow",
      "docs/changelog/*.md": "allow",
      "docs/changelog/**/*.md": "allow",
      "docs/guides/*.md": "allow",
      "docs/guides/**/*.md": "allow",
      "docs/api/*.md": "allow",
      "docs/api/**/*.md": "allow",
      "docs/release-notes/*.md": "allow",
      "docs/release-notes/**/*.md": "allow"
    },
    "bash": "deny",
    "webfetch": "allow",
    "websearch": "deny",
    "todowrite": "deny",
    "lsp": "deny",
    "skill": "allow",
    "task": {
      "*": "deny"
    }
  }
}

export function openCodeRolePermission(name: string): OpenCodeRolePermission {
  const permission = ROLE_PERMISSIONS[name]
  if (!permission) throw new Error(`No hay politica OpenCode para el agente ${name}`)
  return permission
}
