# --- CONFIGURACIÓN GENERAL ---
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -sg escape-time 10

# --- GESTOR DE PLUGINS (TPM) ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'alexwforsythe/tmux-which-key'

# --- VENTANA FLOTANTE (Alt + g) ---
bind-key -n M-g if-shell -F '#{==:#{session_name},scratch}' {
  detach-client
} {
  display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}

# --- TEMA CATPPUCCIN MOCHA ---
set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @ukiyo-theme 'catppuccin/mocha'
set -g @ukiyo-plugins "cpu-usage ram-usage git time"
set -g @ukiyo-time-format "%d/%m/%y %H:%M"
set -g @ukiyo-ignore-window-colors true
set -g status-position bottom

# --- TERMINAL Y COLOR ---
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",xterm-ghostty:RGB"
set -s extended-keys off

# --- MODO VI Y COPIAR ---
set -g mode-keys vi
if-shell "uname | grep -q Darwin" {
  bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
} {
  bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip"
}

# --- KEYMAPS ---
unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"

set -g mouse on

bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"

# --- TPM ---
run '~/.tmux/plugins/tpm/tpm'
